/**
 * radio Component
 * Generated by Basalt Visual Builder
 */

export interface radioProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'default' | 'selected' | 'disabled';
  size?: 'md';
  on/off?: boolean;
  copy?: string;
  icon?: React.ReactNode;
  children?: React.ReactNode;
}

export function radio({
  variant = 'default',
  size = 'md',
  on/off,
  copy,
  icon,
  children,
  className = "",
  ...props
}: radioProps) {
  const variantColor: Record<string, string> = {
    'default': 'var(--component-radio-default)',
    'selected': 'var(--component-radio-selected)',
    'disabled': 'var(--component-radio-disabled)'
  };

  const sizePadding: Record<string, string> = {
    'md': '10px 20px'
  };

  const sizeFontSize: Record<string, string> = {
    'md': '1rem'
  };

  return (
    <button
      className={className}
      style={{
        background: variantColor[variant],
        padding: sizePadding[size],
        fontSize: sizeFontSize[size],
        borderRadius: '8px',
        border: 'none',
        cursor: 'pointer',
        display: 'inline-flex',
        alignItems: 'center',
        gap: '8px',
      }}
      {...props}
    >
      {icon && <span className="inline-flex">{icon}</span>}
      {children}
    </button>
  );
}
