/**
 * Toggle Component
 * Generated by Basalt Visual Builder
 */

export interface ToggleProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary';
  size?: 'sm' | 'md' | 'lg';
  icon?: React.ReactNode;
  children?: React.ReactNode;
}

export function Toggle({
  variant = 'primary',
  size = 'sm',
  icon,
  children,
  className = "",
  ...props
}: ToggleProps) {
  const variantColor: Record<string, string> = {
    'primary': 'var(--component-toggle-primary)',
    'secondary': 'var(--component-toggle-secondary)'
  };

  const sizePadding: Record<string, string> = {
    'sm': '8px 16px',
    'md': '10px 20px',
    'lg': '14px 28px'
  };

  const sizeFontSize: Record<string, string> = {
    'sm': '0.875rem',
    'md': '1rem',
    'lg': '1.125rem'
  };

  return (
    <button
      className={className}
      style={{
        background: variantColor[variant],
        padding: sizePadding[size],
        fontSize: sizeFontSize[size],
        borderRadius: '8px',
        border: 'none',
        cursor: 'pointer',
        display: 'inline-flex',
        alignItems: 'center',
        gap: '8px',
      }}
      {...props}
    >
      {icon && <span className="inline-flex">{icon}</span>}
      {children}
    </button>
  );
}
